### ISSUE TITLE
Class Not Found

### ISSUE THREAD

**Issue by feyzprod** [paysafegroup/paysafe_sdk_php#11]
/card-payment-simple.php - Class 'Paysafe\PaysafeApiClient' not found in /home/seb/Downloads/paysafe/sample/card-payment-simple.php on line 9

Is it normal ? I am on Ubuntu 14.04

**Comment by PayLeaseBrian** [comment]
You're likely running into the autoloader issue discussed here: https://github.com/paysafegroup/paysafe_sdk_php/issues/7#issuecomment-296691587

**Comment by feyzprod** [comment]
I updated source/paysafe.php with this:

```
function __PaysafeAutoloader($className)
{
    $classPath = str_replace("\\", DIRECTORY_SEPARATOR, lcfirst($className));
    $classFile = __DIR__ . DIRECTORY_SEPARATOR . $classPath . '.php';
    if (file_exists($classFile)) {
        require_once( $classFile );
    }
}
```
It's working now but I'm not sure if it is going to work for all file/class ...

**Comment by PayLeaseBrian** [comment]
I think it will probably work out for you, actually. You've lowercased the `P` in Paysafe, and I think the remainder of the path/filename should have case that matches the namespace/class exactly.

**Comment by asawarivaidya** [comment]
Fixed the autoloader issue, please check the latest release 1.0.3.
Thanks.
