### ISSUE TITLE
Found issue with auto-loading

### ISSUE THREAD

**Issue by hirenaspl** [paysafegroup/paysafe_sdk_php#14]
I fixed with below steps:

1)  lib/vendor/paysafegroup/paysafe_sdk_php/source/paysafe.php:

function __PaysafeAutoloader($className)
{
    $classPath = str_replace("\\", DIRECTORY_SEPARATOR, $className);

    if (($classFile = realpath(__DIR__ . DIRECTORY_SEPARATOR . $classPath . '.php'))) {
        require_once( $classFile );
    }
}

Removed use of strtolower function with first line of function.

2) Renamed directory from "lib/vendor/paysafegroup/paysafe_sdk_php/source/paysafe" to "lib/vendor/paysafegroup/paysafe_sdk_php/source/Paysafe"

Please check - my side that is working now.

Thanks.

**Comment by asawarivaidya** [comment]
Fixed it with these suggestions. Thanks.
