### ISSUE TITLE
can't authorize a payment with cents

### ISSUE THREAD

**Issue by securedinvestmentcorp** [paysafegroup/paysafe_sdk_php#18]
`$auth = new Authorization(array(
     'merchantRefNum' => "0f8fad5bd9cb469fa16570867728950e",
     'amount' => 555,
     'settleWithAuth' => true,
     'card' => array(
          'cardNum' => "4111111111111111",
          'cvv' => '123',
          'cardExpiry' => array(
                'month' => "06",
                'year' => "2020",
          )
     ),
     'billingDetails' => array(
          'zip' => "M5H 2N2"
     )
));
 
$response = $client->cardPaymentService()->authorize($auth);`

if the amount is 555.50 it fails saying it needs to be a Int

**Comment by francoisneron** [comment]
@securedinvestmentcorp, you have to pass the amount in cent. For example, 555.50 would be 55550 for an Integer object. It will be converted to the appropriate decimal in our system depending on the currency.
