### ISSUE TITLE
Class `Paysafe\ThreeDSecureService` not found

### ISSUE THREAD

**Issue by anothy** [paysafegroup/paysafe_sdk_php#22]
Hi,

In `PaysafeApiClient` the method `threeDSecureService()` returns `ThreeDSecureService`. I'm getting a fatal error saying class `Paysafe\ThreeDSecureService` cannot be found.  Simple fix was to just change `ThreeDSecureService` to `ThreeDsecureService` (lowercase 's' in secure). 

Thanks,

Anthony

**Comment by francoisneron** [comment]
The real issue is here @anothy 
https://github.com/paysafegroup/paysafe_sdk_php/blob/cf5918a2989deade88b2736093783af8e1a3898a/source/Paysafe/ThreeDsecureService.php

As you can see the class name is incorrect, please submit a pull request to fix this issue (file name and class name).

**Comment by francoisneron** [comment]
https://github.com/paysafegroup/paysafe_sdk_php/pull/24

**Comment by Spikes042** [comment]
Can this be released, please
