### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by Voyager-Two** [paysafegroup/paysafe_sdk_php#30]
Hello,

`1.0.3` is outdated and is missing important fixes such as https://github.com/paysafegroup/paysafe_sdk_php/commit/ed4c707651c932d2ea620c5515b4f2aaf66c7f8f

> https://github.com/paysafegroup/paysafe_sdk_php/releases

Thank you

**Comment by Spikes042** [comment]
@OpusSdkSupport The new v1.1.0 release is still not pushed to composer (https://packagist.org/packages/paysafegroup/paysafe_sdk_php)
