### ISSUE TITLE
StoredCredential object doesn't support parameters outlined in documentation

### ISSUE THREAD

**Issue by andychute** [paysafegroup/paysafe_sdk_php#38]
When providing the `initialTransactionId` and / or the `externalInitialTransactionId` parameters, as outlined within documentation, to an authorization request using the SDK, they are stripped out and ignored.  

See:
https://developer.paysafe.com/en/cards/api/#/introduction/complex-json-objects/storedcredential

Opened a Pull Request at:
https://github.com/paysafegroup/paysafe_sdk_php/pull/37#issue-1384254382

**Comment by nstanchev** [comment]
The properties are added.
