### ISSUE TITLE
Customer vault example in documentation does not work

### ISSUE THREAD

**Issue by andychute** [paysafegroup/paysafe_sdk_php#8]
Example for creating a customer profile using a single-use token via the PHP SDK outlined at the following page does not function:
https://developer.paysafe.com/en/sdks/server-side/php/customer-vault/

Code outlined is as follows:
```
$profile = new Profile(array(
	"merchantCustomerId" => $merchantCustomerId,
	"locale" => "en_US",
	"firstName" => "John",
	"lastName" => "Smith",
	"email" => "john.smith@somedomain.com",
	"phone" => "713-444-5555",
	"card" => array(
		'singleUseToken' => "SCrGrrRANmOVtcVc"
	)
));
$response = $client->customerVaultService()->createProfile($profile);
```

However, the customer vault profile object ignores the 'card' property, so it is never stored and encoded in the request to create a vault profile.   Example should not outline this process, or the 'card' property should be added to the field types in [source/paysafe/customervault/profile.php](https://github.com/paysafegroup/paysafe_sdk_php/blob/master/source/paysafe/customervault/profile.php) and the optional fields set in [source/paysafe/customervaultservice.php](https://github.com/paysafegroup/paysafe_sdk_php/blob/master/source/paysafe/customervaultservice.php)

**Comment by asawarivaidya** [comment]
Fixed. Documentation is correct, 'card' property was not added in CustomerVault/Profile.php, however, now it is added and also have set card property as optional field for create profile request in CustomerVaultService.php
